### ISSUE TITLE
we decided for clearer design to wrap textView to scrollView and to add a function for scrolling to end of textView after each update

### ISSUE THREAD

**Issue by ermolnik** [Android-Academy-Global/fundamentals-2020-assignments#33]
we decided for clearer design to wrap textView to scrollView and to add a function for scrolling to end of textView after each update

_Originally posted by @ermolnik in https://github.com/Android-Academy-Global/fundamentals-2020-assignments/pull/29#discussion_r535690129_

**Comment by emartynov** [comment]
Github, this is the ticket for following up #29
